/*
 * EmpAddInfor.java
 *
 * Created on __DATE__, __TIME__
 */

package com.csust.views;

import java.util.List;
import java.util.Vector;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.csust.dao.EmpDAOImpl;
import com.csust.listener.EmpAddInfor_ActionListener;
import com.csust.model.Employee;
import com.csust.utils.PositionHelper;
import com.csust.utils.TextUtils;


public class EmpAddInfor extends javax.swing.JDialog {

	private Vector<Vector<Object>> data;
	private Vector<String> titles;

	/** Creates new form EmpAddInfor */
	public EmpAddInfor(java.awt.Frame parent, boolean modal,
			Vector<Vector<Object>> data, Vector<String> titles) {
		super(parent, modal);
		this.data = data;
		this.titles = titles;
		initComponents();
		PositionHelper.centerInScreen(this);
		setVisible(true);
	}

	public void btn_AddPerformed() {
		String name = jTextField1.getText().toString();
		String num = jTextField2.getText().toString();
		String position = jComboBox1.getSelectedItem().toString();
//		System.out.println(position);
		String password = jTextField4.getText().toString();
		List<Employee> list = new EmpDAOImpl().getAllEmps();
		for (Employee emp : list) {
			if (num.equals(emp.getJobID())) {
				JOptionPane.showMessageDialog(this, "你输入的员工编号已存在");
				return;
			}
		}
		if (TextUtils.isNull(name) || TextUtils.isNull(num)
				|| TextUtils.isNull(position) || TextUtils.isNull(password)) {
			JOptionPane.showMessageDialog(this, "请检查您的输入信息");
		} else {
			Employee employee = new Employee();
			employee.setJobID(num);
			employee.setName(name);
			employee.setPassword(password);
			employee.setPosition(position);
			boolean insert = new EmpDAOImpl().insertEmp(employee);
			if (insert) {
				Vector<Object> item = new Vector<Object>();
				item.addElement(employee.getName());
				item.addElement(employee.getJobID());
				item.addElement(employee.getPosition());
				item.addElement(employee.getPassword());
				data.add(item);
			}
			PersonManageFrame fatherFrame = (PersonManageFrame) getParent();
			fatherFrame.jTable1.setModel(new DefaultTableModel(data, titles));
			JOptionPane.showMessageDialog(this, "插入成功");
			dispose();
		}
	}

	public void btn_ClearPerformed() {
		jTextField1.setText("");
		jTextField2.setText("");
		jTextField4.setText("");
//		jTextField3.setText("");
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jTextField1 = new javax.swing.JTextField();
		jTextField2 = new javax.swing.JTextField();
		jTextField4 = new javax.swing.JTextField();
		jComboBox1 = new javax.swing.JComboBox();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setText("\u5458\u5de5\u4fe1\u606f");

		jLabel2.setText("\u59d3\u540d\uff1a");

		jLabel3.setText("\u804c\u5de5\u53f7\uff1a");

		jLabel4.setText("\u804c\u4f4d\uff1a");

		jLabel5.setText("\u5bc6\u7801\uff1a");

		jButton1.setText("\u6dfb\u52a0");
		jButton1.setActionCommand("add");
		jButton1.addActionListener(new EmpAddInfor_ActionListener(this));

		jButton2.setText("\u6e05\u7a7a");
		jButton2.setActionCommand("clear");
		jButton2.addActionListener(new EmpAddInfor_ActionListener(this));


		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"收银员", "仓库管理员" }));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(166, Short.MAX_VALUE)
								.addComponent(jLabel1).addGap(162, 162, 162))
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(64, 64,
																		64)
																.addComponent(
																		jButton1,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		151,
																		Short.MAX_VALUE)
																.addGap(27, 27,
																		27)
																.addComponent(
																		jButton2,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		128,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														javax.swing.GroupLayout.Alignment.LEADING,
														layout.createSequentialGroup()
																.addGap(31, 31,
																		31)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel2)
																				.addComponent(
																						jLabel3)
																				.addComponent(
																						jLabel4)
																				.addComponent(
																						jLabel5))
																.addGap(43, 43,
																		43)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						jTextField4)
																				.addComponent(
																						jTextField2)
																				.addComponent(
																						jTextField1,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						188,
																						Short.MAX_VALUE)
																				.addComponent(
																						jComboBox1,
																						0,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE))))
								.addContainerGap(30,
										javax.swing.GroupLayout.PREFERRED_SIZE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel1)
								.addGap(39, 39, 39)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(
														jTextField1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(63, 63, 63)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel3)
												.addComponent(
														jTextField2,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(61, 61, 61)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel4)
												.addComponent(
														jComboBox1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(58, 58, 58)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel5)
												.addComponent(
														jTextField4,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										58, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButton1)
												.addComponent(jButton2))
								.addGap(43, 43, 43)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField4;
	// End of variables declaration//GEN-END:variables

}