/*
 * FunctionFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package com.csust.views;

import com.csust.listener.FunctionFrame_ActionListener;
import com.csust.model.Employee;
import com.csust.utils.PositionHelper;

public class FunctionFrame extends javax.swing.JFrame {

	private Employee employee;

	/** Creates new form FunctionFrame */
	public FunctionFrame(Employee emp) {
		this.employee = emp;
		initComponents();
		setVisible(true);
	}
	
	
	
	/**
	 * 销售管理
	 */
	public void sellActionPerformed() {
		new MainWindow(employee);
//		dispose();
	}

	public void peopleManActionPerformed() {
		new PersonManageFrame(employee);
	}

	public void InActionPerformed() {
//		new EmpAddInfor(this, true,null,null);
		new GarageManageFrame();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton1.setActionCommand("销售");
		jButton2.setActionCommand("入库");
		jButton3.setActionCommand("人员");
		jButton1.addActionListener(new FunctionFrame_ActionListener(this));
		jButton2.addActionListener(new FunctionFrame_ActionListener(this));
		jButton3.addActionListener(new FunctionFrame_ActionListener(this));
		
		if(employee.getPosition().equals("仓库管理员")){
			jButton1.setEnabled(false);
			jButton3.setEnabled(false);
		}else if(employee.getPosition().equals("收银员")){
			jButton2.setEnabled(false);
			jButton3.setEnabled(false);
		}
		

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jButton1.setText("\u9500\u552e\u7ba1\u7406");

		jButton2.setText("仓库管理");

		jButton3.setText("\u4eba\u5458\u7ba1\u7406");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(jButton1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										182,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jButton2,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										193,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jButton3,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										195, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createParallelGroup(
						javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jButton1,
								javax.swing.GroupLayout.DEFAULT_SIZE, 180,
								Short.MAX_VALUE)
						.addComponent(jButton2,
								javax.swing.GroupLayout.DEFAULT_SIZE, 180,
								Short.MAX_VALUE)
						.addComponent(jButton3,
								javax.swing.GroupLayout.DEFAULT_SIZE, 180,
								Short.MAX_VALUE)));

		pack();
		PositionHelper.centerInScreen(this);
	}// </editor-fold>
		// GEN-END:initComponents

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	// End of variables declaration//GEN-END:variables

}