/*
 * GarageManageFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package com.csust.views;

import java.awt.Color;
import java.awt.Font;
import java.util.List;
import java.util.Vector;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.csust.dao.EmpDAOImpl;
import com.csust.dao.YaoDAOImpl;
import com.csust.listener.GarageManageFrame_ActionListener;
import com.csust.model.Yao;
import com.csust.utils.ExcelUtils;
import com.csust.utils.PositionHelper;


public class GarageManageFrame extends javax.swing.JFrame {

	private DefaultTableModel tableModel;
	private List<Yao> list;
	private Vector<Vector<Object>> data;
	private Vector<String> columnNames;

	/** Creates new form GarageManageFrame */
	public GarageManageFrame() {
		initComponents();
		setTitle("仓库管理");
		list = new YaoDAOImpl().getAllYao();
		data = new Vector<Vector<Object>>();
		columnNames = new Vector<String>();
		for (Yao yao : list) {
			Vector<Object> item = new Vector<Object>();
			item.addElement(yao.getBianhao());
			item.addElement(yao.getName());
			item.addElement(yao.getType());
			item.addElement(yao.getSellPrice());
			item.addElement(yao.getPifaPrice());
			item.addElement(yao.getRemainCount());
			data.add(item);
		}
		columnNames.addElement("编号");
		columnNames.addElement("名称");
		columnNames.addElement("类型");
		columnNames.addElement("售价");
		columnNames.addElement("批发价");
		columnNames.addElement("库存");

		tableModel = new DefaultTableModel(data, columnNames);
		jTable1.setModel(tableModel);
		// setSize(800, 480);
		jTable1.getTableHeader().setBackground(new Color(166, 202, 240));
		// Microsoft YaHei UI 20 Plain
		jTable1.getTableHeader().setFont(
				new Font("Microsoft YaHei UI", Font.BOLD, 24));
		PositionHelper.centerInScreen(this);
		setVisible(true);
	}

	public void btn_updatePerformed() {
//		System.out.println("修改");
		Yao selectYao = null;
		list = new YaoDAOImpl().getAllYao();
		int row = jTable1.getSelectedRow();
		if(row==-1){
			JOptionPane.showMessageDialog(this, "请选择要修改的药品");
			return;
		}
		String selectedBianhao = (String) jTable1.getValueAt(row, 0);
		for(Yao yao:list){
			if(yao.getBianhao().equals(selectedBianhao)){
				selectYao = yao;
			}
		}
		new UpdateGoodsDia(this, true, selectYao,list);
	}

	public void btn_deletePerformed() {
//		System.out.println("删除");
		int row = jTable1.getSelectedRow();
		DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
		if(row==-1){
			JOptionPane.showMessageDialog(this, "请选择您要删除的药品");
			return;
		}
		String bianhao = (String) model.getValueAt(row, 0);
		String name = (String) model.getValueAt(row, 1);
		if(JOptionPane.showConfirmDialog(this, "确认删除编号为: "+bianhao+" 的  "+name+" 吗?")!=0){
			return;
		}
//		System.out.println(JOptionPane.showConfirmDialog(this, "确认删除编号为"+bianhao+"的"+name+"吗?"));
		data.remove(row);
		jTable1.setModel(new DefaultTableModel(data, columnNames));
		boolean delete = new YaoDAOImpl().deleteYao(bianhao);
		if(delete){
			JOptionPane.showMessageDialog(this, "删除成功");
		}
	}

	public void btn_inGoodPerformed() {
//		System.out.println("进货");
		new InGoodsInfor(this, true);
	}

	public void btn_daochuPerformed() {
//		System.out.println("导出");
		JFileChooser chooser = new JFileChooser();
		if(chooser.showSaveDialog(this)==1){
			return;
		}
		String path = chooser.getCurrentDirectory().getPath();
		String path1 = path.replace('\\','/');
		String fileName = chooser.getSelectedFile().getName();
		String realPath = path1+"/"+fileName;
		
		list = new YaoDAOImpl().getAllYao();
//		int row = jTable1.getRowCount();
//		String remain[] = new String[row];
//		for(int i =0;i<row;i++){
//			String remainCount = String.valueOf((Integer) jTable1.getValueAt(i, 5));
//			remain[i] = remainCount;
//			System.out.println(list.get(i).toString()+",库存："+remainCount);
//		}
		if(ExcelUtils.exportYaoTypeExcel(list,realPath)){
			JOptionPane.showMessageDialog(this, "导出成功");
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		
		jButton1.setActionCommand("update");
		jButton1.addActionListener(new GarageManageFrame_ActionListener(this));
		
		jButton2.setActionCommand("delete");
		jButton2.addActionListener(new GarageManageFrame_ActionListener(this));
		
		jButton3.setActionCommand("inGoods");
		jButton3.addActionListener(new GarageManageFrame_ActionListener(this));
		
		jButton4.setActionCommand("daochu");
		jButton4.addActionListener(new GarageManageFrame_ActionListener(this));

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));

		jTable1.setBackground(new java.awt.Color(255, 251, 240));
		jTable1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20));
		jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
		jTable1.setRowHeight(30);
		jTable1.setRowMargin(10);

		jScrollPane1.setViewportView(jTable1);

		jButton1.setText("\u4fee\u6539");

		jButton2.setText("删除");

		jButton3.setText("\u8fdb\u8d27");

		jButton4.setText("\u5bfc\u51fa");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										835,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										46, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addComponent(
														jButton4,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(
														jButton3,
														javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(
														jButton2,
														javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(
														jButton1,
														javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														99,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(40, 40, 40)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jScrollPane1,
						javax.swing.GroupLayout.DEFAULT_SIZE, 683,
						Short.MAX_VALUE)
				.addGroup(
						layout.createSequentialGroup().addGap(179, 179, 179)
								.addComponent(jButton1).addGap(57, 57, 57)
								.addComponent(jButton2).addGap(61, 61, 61)
								.addComponent(jButton3).addGap(65, 65, 65)
								.addComponent(jButton4)
								.addContainerGap(189, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
		// GEN-END:initComponents

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JScrollPane jScrollPane1;
	public javax.swing.JTable jTable1;
	// End of variables declaration//GEN-END:variables

}