/*
 * InGoodsInfor.java
 *
 * Created on __DATE__, __TIME__
 */

package com.csust.views;

import java.awt.Color;
import java.awt.Font;
import java.awt.JobAttributes;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.csust.dao.YaoDAOImpl;
import com.csust.listener.InGoodsListener;
import com.csust.model.Yao;
import com.csust.utils.PositionHelper;
import com.csust.utils.SimpleCommIO;
import com.csust.utils.TextUtils;


public class InGoodsInfor extends javax.swing.JDialog implements ActionListener {

	private Vector<Vector<Object>> data = new Vector<Vector<Object>>();
	private Vector<Object> titles = new Vector<Object>();
	private List<Yao> list;
	private boolean find = false;

	/** Creates new form InGoodsInfor */
	public InGoodsInfor(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		list = new YaoDAOImpl().getAllYao();
		initComponents();
		PositionHelper.centerInScreen(this);
		setVisible(true);
	}
	
	

	public void btn_RequestPerformed() {
		find = false;
		// System.out.println("request");
		String bianhao = jTextField1.getText().toString();
		String mingzi = jTextField2.getText().toString();
		if (TextUtils.isNull(bianhao)) {
			JOptionPane.showMessageDialog(this, "编号不能为空");
			return;
		}
		for (Yao yao : list) {
			if (yao.getBianhao().equals(bianhao)) {
				find = true;
				jTextField2.setText(yao.getName());
				jComboBox1.setSelectedItem(yao.getType());
				jTextField3.setText(String.valueOf(yao.getSellPrice()));
				jTextField4.setText(String.valueOf(yao.getPifaPrice()));
				jTextField5.setText(String.valueOf(yao.getRemainCount()));
				jTextField6.setText("0");
			}
		}
		if (find == false) {
			JOptionPane.showMessageDialog(this, "仓库不含有此种药品，请填写信息");
			jTextField2.setText("");
			jComboBox1.setSelectedIndex(0);
			jTextField3.setText("");
			jTextField4.setText("");
			jTextField5.setText("");
			jTextField6.setText("");
		}
	}

	public void btn_InPerformed() {
//		 System.out.println("in");
		String bianhao = jTextField1.getText();
		String mingzi = jTextField2.getText();
		String type = jComboBox1.getSelectedItem().toString();
		String price = jTextField3.getText();
		String pifa = jTextField4.getText();
		String remain = jTextField5.getText();
		String pifaNum = jTextField6.getText();
		if (TextUtils.isNull(bianhao) || TextUtils.isNull(mingzi)
				|| TextUtils.isNull(type) || TextUtils.isNull(price)
				|| TextUtils.isNull(pifa) || TextUtils.isNull(remain)
				|| TextUtils.isNull(pifaNum)) {
			JOptionPane.showMessageDialog(this, "请检查药品信息");
		}
		for (Yao yao : list) {
			if (yao.getName().equals(mingzi) && find == false) {
				JOptionPane.showMessageDialog(this, "您输入的商品名称已存在");
				return;
			}
		}
		Vector<Object> item = new Vector<Object>();
		item.addElement(bianhao);
		item.addElement(mingzi);
		item.addElement(type);
		item.addElement(price);
		item.addElement(pifa);
		item.addElement(pifaNum);
		item.addElement(Double.valueOf(pifa) * Integer.valueOf(pifaNum));
		data.add(item);
		jTable1.setModel(new DefaultTableModel(data, titles));
		jTextField2.setText("");
		jTextField1.setText("");
		jComboBox1.setSelectedIndex(0);
		jTextField3.setText("");
		jTextField4.setText("");
		jTextField5.setText("");
		jTextField6.setText("");
	}

	public void btn_YesPerformed() {
		// System.out.println("yes");
		int row = jTable1.getRowCount();
		//		System.out.println(row);
		if (row == 0) {
			JOptionPane.showMessageDialog(this, "请选择您要添加的药品");
			return;
		}
		new GoodsList(this, true, data, titles);
		dispose();
		GarageManageFrame pareFrame = (GarageManageFrame) getParent();
		pareFrame.dispose();
	}

	public void btn_ClearPerformed() {
		data.removeAllElements();
		jTable1.setModel(new DefaultTableModel(data, titles));
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		
		titles.addElement("编号");
		titles.addElement("名称");
		titles.addElement("类型");
		titles.addElement("售价");
		titles.addElement("批发价");
		titles.addElement("批发数量");
		titles.addElement("总价");

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox();
		jLabel5 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		jTextField4 = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		jTextField5 = new javax.swing.JTextField();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jButton1 = new javax.swing.JButton();
		jButton1.setActionCommand("chaxun");
		jButton1.addActionListener(new InGoodsListener(this));
		jLabel10 = new javax.swing.JLabel();
		jTextField6 = new javax.swing.JTextField();
		jButton2 = new javax.swing.JButton();
		jButton2.setActionCommand("in");
		jButton2.addActionListener(new InGoodsListener(this));
		jButton3 = new javax.swing.JButton();
		jButton3.setActionCommand("queren");
		jButton3.addActionListener(new InGoodsListener(this));
		jButton4 = new javax.swing.JButton();
		jButton4.setActionCommand("qingkong");
		jButton4.addActionListener(new InGoodsListener(this));

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setText("查询");

		jLabel2.setText("\u7f16\u53f7\uff1a");

		jLabel3.setText("\u540d\u79f0\uff1a");

		jLabel4.setText("\u7c7b\u578b\uff1a");

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"中药", "西药", "处方内", "处方外", "非处方内", "非处方外" }));

		jLabel5.setText("\u552e\u4ef7\uff1a");

		jLabel6.setText("\u6279\u53d1\u4ef7\uff1a");

		jLabel7.setText("\u5e93\u5b58\uff1a");

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {

				}, new String[] { "编号", "名称", "类型","售价", "批发价", "批发数量", "总价" }));
		jScrollPane1.setViewportView(jTable1);

		jButton1.setText("\u8bfb\u53d6");

		jLabel10.setText("\u6279\u53d1\u6570\u91cf\uff1a");

		jTextField6.setText("");

		jButton2.setText(">>>");

		jButton3.setText("\u786e\u8ba4");

		jButton4.setText("\u6e05\u7a7a");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(34, 34, 34)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(jLabel10)
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(
																		jLabel4)
																.addComponent(
																		jLabel5)
																.addComponent(
																		jLabel3)
																.addComponent(
																		jLabel2))
												.addComponent(jLabel6)
												.addComponent(jLabel7))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jTextField1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		133,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jButton1,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE))
												.addComponent(jTextField6)
												.addComponent(jTextField5)
												.addComponent(jTextField4)
												.addComponent(jTextField3)
												.addComponent(jTextField2)
												.addComponent(jComboBox1, 0,
														165, Short.MAX_VALUE))
								.addGap(43, 43, 43)
								.addComponent(jButton2)
								.addGap(78, 78, 78)
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										665,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap())
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(623, Short.MAX_VALUE)
								.addComponent(jButton3,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										111,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(189, 189, 189)
								.addComponent(jButton4,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										119,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(179, 179, 179))
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(793, Short.MAX_VALUE)
								.addComponent(jLabel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										136,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(292, 292, 292)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(75,
																										75,
																										75)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														jLabel2)
																												.addGroup(
																														layout.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.BASELINE)
																																.addComponent(
																																		jButton1)
																																.addComponent(
																																		jTextField1,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		javax.swing.GroupLayout.PREFERRED_SIZE)))
																								.addGap(44,
																										44,
																										44)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.TRAILING)
																												.addComponent(
																														jLabel3)
																												.addComponent(
																														jTextField2,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.PREFERRED_SIZE))
																								.addGap(44,
																										44,
																										44)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.BASELINE)
																												.addComponent(
																														jLabel4)
																												.addComponent(
																														jComboBox1,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.PREFERRED_SIZE))
																								.addGap(59,
																										59,
																										59)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.BASELINE)
																												.addComponent(
																														jLabel5)
																												.addComponent(
																														jTextField3,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.PREFERRED_SIZE))
																								.addGap(43,
																										43,
																										43)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														jLabel6)
																												.addComponent(
																														jTextField4,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.PREFERRED_SIZE))
																								.addGap(44,
																										44,
																										44)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.TRAILING)
																												.addComponent(
																														jLabel7)
																												.addComponent(
																														jTextField5,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.PREFERRED_SIZE))
																								.addGap(39,
																										39,
																										39)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.BASELINE)
																												.addComponent(
																														jLabel10,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														37,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addComponent(
																														jTextField6,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.PREFERRED_SIZE))
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																										26,
																										Short.MAX_VALUE))
																				.addGroup(
																						javax.swing.GroupLayout.Alignment.TRAILING,
																						layout.createSequentialGroup()
																								.addContainerGap()
																								.addComponent(
																										jLabel1)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																								.addComponent(
																										jScrollPane1,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										509,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addGap(11,
																										11,
																										11)))
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jButton3,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						34,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jButton4,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						35,
																						javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(288,
																		288,
																		288)
																.addComponent(
																		jButton2)))
								.addContainerGap()));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	public static javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	private javax.swing.JTextField jTextField6;

	// End of variables declaration//GEN-END:variables
	@Override
	public void actionPerformed(ActionEvent e) {
		String command = e.getActionCommand();
		if (command.equals("request")) {
			// System.out.println(ingGoodsInfor);
			btn_RequestPerformed();
		} else if (command.equals("in")) {
			btn_InPerformed();
		} else if (command.equals("yes")) {
			btn_YesPerformed();
		} else if (command.equals("clear")) {
			btn_ClearPerformed();
		}
	}

}