/*
 * PersonManageFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package com.csust.views;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.List;
import java.util.Vector;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.csust.dao.EmpDAOImpl;
import com.csust.listener.PersonManageFrame_ActionListener;
import com.csust.model.Employee;
import com.csust.utils.ExcelUtils;
import com.csust.utils.PositionHelper;
import com.sun.org.apache.bcel.internal.generic.IF_ACMPEQ;


public class PersonManageFrame extends javax.swing.JFrame {
	
	private List<Employee> list = new EmpDAOImpl().getAllEmps();

	private Vector<Vector<Object>> data = new Vector<Vector<Object>>();
	private Vector<String> titles = new Vector<String>();
	/** Creates new form PersonManageFrame */
	public PersonManageFrame(final Employee emp) {
		initComponents();
		setData();
		PositionHelper.centerInScreen(this);
		setVisible(true);
	}
	
	public void btn_addPerformed() {
		new EmpAddInfor(this, true,data,titles);
	}
	
	public void btn_deletePerformed() {
		int row = jTable1.getSelectedRow();
		DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
		if(row==-1){
			JOptionPane.showMessageDialog(this, "请选择您要删除的职员");
			return;
		}
		String jobID = (String) model.getValueAt(row, 1);
		data.remove(row);
		jTable1.setModel(new DefaultTableModel(data, titles));
		boolean delete = new EmpDAOImpl().deleteEmp(jobID);
		if(delete){
			JOptionPane.showMessageDialog(this, "删除成功");
		}
	}
	
	public void btn_DaochuPerformed(){
		JFileChooser chooser = new JFileChooser();
		if(chooser.showSaveDialog(this)==1){
			return;
		}
		String path = chooser.getCurrentDirectory().getPath();
		String path1 = path.replace('\\','/');
		String fileName = chooser.getSelectedFile().getName();
		String realPath = path1+"/"+fileName;
//		System.out.println(path1);
//		System.out.println(realPath);
//		System.out.println(realPath);
		//取消 1 保存0
		list = new EmpDAOImpl().getAllEmps();
		if(ExcelUtils.exportStaffExcel(list,realPath)){
			JOptionPane.showMessageDialog(this, "导出成功");
		}
	}

	private void setData() {
		for(Employee emp:list){
			Vector<Object> item = new Vector<Object>();
			item.addElement(emp.getName());
			item.addElement(emp.getJobID());
			item.addElement(emp.getPosition());
			item.addElement(emp.getPassword());
			data.add(item);
		}
		
		titles.addElement("姓名");
		titles.addElement("工作号");
		titles.addElement("职位");
		titles.addElement("密码");
		
		jTable1.setModel(new DefaultTableModel(data, titles));
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setText("\u804c\u5de5\u4fe1\u606f\u8868");
		

		jButton1.setText("\u6dfb\u52a0");
		jButton1.setActionCommand("add");
		jButton1.addActionListener(new PersonManageFrame_ActionListener(this));

		jButton2.setText("\u5220\u9664");
		jButton2.setActionCommand("delete");
		jButton2.addActionListener(new PersonManageFrame_ActionListener(this));

		jButton3.setText("\u5bfc\u51fa");
		jButton3.setActionCommand("daochu");
		jButton3.addActionListener(new PersonManageFrame_ActionListener(this));
		
		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 22));
		jLabel1.setText("职工信息表");

		jTable1.setBackground(new Color(255, 251, 240));
		jTable1.getTableHeader().setBackground(new Color(166, 202, 240));
		// Microsoft YaHei UI 20 Plain
		jTable1.getTableHeader().setFont(
				new Font("Microsoft YaHei UI", Font.BOLD, 24));
		jTable1.setRowHeight(30);
		jTable1.setRowMargin(10);

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {}, new String[] { "姓名",
						"职工号", "职位", "密码" }));
		jScrollPane1.setViewportView(jTable1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(33, 33,
																		33)
																.addComponent(
																		jScrollPane1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		513,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(44, 44,
																		44)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						jButton3,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(
																						jButton2,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(
																						jButton1,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						112,
																						Short.MAX_VALUE)))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(240,
																		240,
																		240)
																.addComponent(
																		jLabel1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		214,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap(41, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(
																		jLabel1)
																.addGap(20, 20,
																		20)
																.addComponent(
																		jScrollPane1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(99, 99,
																		99)
																.addComponent(
																		jButton1)
																.addGap(94, 94,
																		94)
																.addComponent(
																		jButton2)
																.addGap(98, 98,
																		98)
																.addComponent(
																		jButton3)))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents


	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JScrollPane jScrollPane1;
	public javax.swing.JTable jTable1;
	// End of variables declaration//GEN-END:variables

}