/*
 * YaoList.java
 *
 * Created on __DATE__, __TIME__
 */

package com.csust.views;

import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;

import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import com.csust.dao.YaoDAOImpl;
import com.csust.listener.YaoList_ActionListener;
import com.csust.model.Yao;
import com.csust.utils.ExcelUtils;
import com.csust.utils.PositionHelper;


public class YaoList extends javax.swing.JDialog {

	private Vector<Vector<Object>> data;
	private Vector<String> titles;
	/** Creates new form YaoList */
	public YaoList(java.awt.Frame parent, boolean modal,
			Vector<Vector<Object>> data, Vector<String> titles, int sum) {
		super(parent, modal);
		this.data = data;
		this.titles = titles;
		setTitle("您的发票");
		initComponents();
		jTable1.setModel(new DefaultTableModel(data, titles));
		jLabel3.setText(String.valueOf(sum) + " 元");
		PositionHelper.centerInScreen(this);
		setVisible(true);
	}

	public void btn_querenPerformed() {
		TableModel model = jTable1.getModel();
		int yaoNums = model.getRowCount();
		int nums[] = new int[yaoNums];
		String bianhao[] = new String[yaoNums];
		for(int i=0;i<yaoNums;i++){
			int sellCountInt =  (Integer) model.getValueAt(i, 4);
			String bianHao = (String) model.getValueAt(i, 0);
			nums[i]=sellCountInt;
			bianhao[i] = bianHao;
//			System.out.println(nums[i]+" "+bianhao[i]);
		}
		MainWindow window = (MainWindow) getParent();
		TableModel old = window.jTable1.getModel();
		int oldRows = old.getRowCount();
//		System.out.println(oldRows);
		for(int i=0;i<oldRows;i++){
			String oldValue = (String) old.getValueAt(i, 0);
			for(int j=0;j<yaoNums;j++){
				if(oldValue.equals(bianhao[j])){
					int oldCount = (Integer) old.getValueAt(i, 5);
					int newCount = oldCount -(Integer) model.getValueAt(j, 4);
					old.setValueAt(newCount, i, 5);
					boolean rs= updateDataBase(oldValue,newCount);
//					System.out.println(rs);
				}
			}
		}
		dispose();
	}

	

	private boolean updateDataBase(String oldValue,int newCount) {
		return new YaoDAOImpl().updateYao(oldValue,newCount);
	}

	public void btn_daochuPerformed() {
		JFileChooser chooser = new JFileChooser();
		if(chooser.showSaveDialog(this)==1){
			return;
		}
		String path = chooser.getCurrentDirectory().getPath();
		String path1 = path.replace('\\','/');
		String fileName = chooser.getSelectedFile().getName();
		String realPath = path1+"/"+fileName;
		int row = jTable1.getRowCount();
		String num[] = new String[row];
		List<Yao> yaos = new ArrayList<Yao>();
		for(int i=0;i<row;i++){
			Yao yao = new Yao();
			yao.setBianhao((String)data.elementAt(i).get(0));
			yao.setName((String)data.elementAt(i).get(1));
			yao.setType((String)data.elementAt(i).get(2));
			yao.setSellPrice((Double)data.elementAt(i).get(3));
			num[i] =  data.elementAt(i).get(4)+"";
			yaos.add(yao);
//			System.out.println(yao.toString()+",数量："+num[i]);
		}
		if(ExcelUtils.exportSellExcel(yaos,num,realPath)){
			JOptionPane.showMessageDialog(this, "导出成功");
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel("您的发票", JLabel.CENTER);
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 22));
		jLabel1.setText("\u60a8\u7684\u53d1\u7968");

		jTable1.setBackground(new Color(255, 251, 240));
		jTable1.getTableHeader().setBackground(new Color(166, 202, 240));
		// Microsoft YaHei UI 20 Plain
		jTable1.getTableHeader().setFont(
				new Font("Microsoft YaHei UI", Font.BOLD, 24));
		jTable1.setRowHeight(30);
		jTable1.setRowMargin(10);
		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {

				}, new String[] { "编号", "名称", "类型", "售价", "数量", "总价" }));
		jScrollPane1.setViewportView(jTable1);

		jLabel2.setText("\u603b\u4ef7\uff1a");

		jLabel3.setText("总价");

		jButton1.setText("\u786e\u8ba4");
		jButton1.setActionCommand("queren");
		jButton1.addActionListener(new YaoList_ActionListener(this));

		jButton2.setText("\u5bfc\u51fa");
		jButton2.setActionCommand("daochu");
		jButton2.addActionListener(new YaoList_ActionListener(this));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(183,
																		183,
																		183)
																.addComponent(
																		jLabel1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		267,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(30, 30,
																		30)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						jScrollPane1,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						560,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel2)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										jLabel3)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										Short.MAX_VALUE)
																								.addComponent(
																										jButton1)
																								.addGap(42,
																										42,
																										42)
																								.addComponent(
																										jButton2)
																								.addGap(26,
																										26,
																										26)))))
								.addContainerGap(34, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel1)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										352,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										12, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(jLabel3)
												.addComponent(jButton1)
												.addComponent(jButton2))
								.addContainerGap()));

		pack();
	}// </editor-fold>
		// GEN-END:initComponents

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	// End of variables declaration//GEN-END:variables

}